[target.wasm64-unknown-unknown]
rustflags = [
  '--cfg', 'getrandom_backend="custom"',
  "-C", "target-feature=+simd128",
  "-C", "link-arg=--max-memory=17179869184", # 16 GiB
  "-C", "link-args=-z stack-size=536870912", # 512 MiB
]